package com.baihe.lib_common.constant

object KeyConstant {
    const val KEY_CUSTOMER = "KEY_CUSTOMER"
    const val KEY_CUSTOMER_ID = "KEY_CUSTOMER_ID"
    const val KEY_CUSTOMER_NAME = "KEY_CUSTOMER_NAME"
    const val KEY_CUSTOMER_IDENTITY = "KEY_CUSTOMER_IDENTITY"
    const val KEY_CUSTOMER_IDENTITY_TXT = "KEY_CUSTOMER_IDENTITY_TXT"
    const val KEY_CUSTOMER_PHONE_PLAIN_TXT = "KEY_CUSTOMER_PHONE_PLAIN_TXT"
    const val KEY_CUSTOMER_PHONE_CIPHER_TXT = "KEY_CUSTOMER_PHONE_CIPHER_TXT"
    const val KEY_CUSTOMER_WECHAT = "KEY_CUSTOMER_WECHAT"
}